# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Specify version update preferences
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
    # Assign reviewers
    reviewers:
      - "MSSkowron"
      - "Kawron"
    # Group dependencies into single PR
    groups:
      # Group production dependencies
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      prefix-development: "npm dev"
      include: "scope"
